services:
  - type: web
    name: discord-ip-checker
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -u main.py
    plan: free
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHONUNBUFFERED
        value: 1
