services:
  - type: web
    name: discord-ip-checker
    runtime: python
    region: oregon  # Ganti: singapore, frankfurt, oregon
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    plan: free
